2024-09-07 19:47:26,421 : INFO : root : Loading config.
2024-09-07 19:47:26,426 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-09-07 19:47:26,427 : WARNING : ConfigProcessor : Config file in cache changed: C:\Users\dorus\OneDrive\Documents\Pinball\PortalPinball-V4.0\machinefolder\config\config.yaml
2024-09-07 19:47:26,427 : INFO : ConfigProcessor : Loading config from file C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\mpfconfig.yaml.
2024-09-07 19:47:26,445 : INFO : ConfigProcessor : Loading config: C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\mpfconfig.yaml
2024-09-07 19:47:26,445 : INFO : ConfigProcessor : Loading config from file C:\Users\dorus\OneDrive\Documents\Pinball\PortalPinball-V4.0\machinefolder\config\config.yaml.
2024-09-07 19:47:26,447 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\OneDrive\Documents\Pinball\PortalPinball-V4.0\machinefolder\config\config.yaml
2024-09-07 19:47:26,448 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\OneDrive\Documents\Pinball\PortalPinball-V4.0\machinefolder\config\hardware.yaml
2024-09-07 19:47:26,449 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\OneDrive\Documents\Pinball\PortalPinball-V4.0\machinefolder\config\hardware-coils.yaml
2024-09-07 19:47:26,453 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\OneDrive\Documents\Pinball\PortalPinball-V4.0\machinefolder\config\hardware-switches.yaml
2024-09-07 19:47:26,456 : INFO : ConfigProcessor : Loading config: C:\Users\dorus\OneDrive\Documents\Pinball\PortalPinball-V4.0\machinefolder\config\hardware-devices.yaml
2024-09-07 19:47:26,460 : INFO : ConfigProcessor : Config file cache created: C:\Users\dorus\AppData\Local\Temp\636ce416879e362e618e72aa23ee7aae.mpf_cache
2024-09-07 19:47:26,574 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\bb22be71dc4df7511e561cdf1fc10b40.mpf_cache
2024-09-07 19:47:26,575 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\d8bc63701c1a2ad1653a8cc5aec9548a.mpf_cache
2024-09-07 19:47:26,575 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev4
2024-09-07 19:47:26,575 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2024-09-07-19-47-26-mpf-Gaming_Dorus.log', 'pause': False, 'production': False, 'text_ui': True, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': 'virtual', 'syslog_address': None, 'mc_file_name': None, 'no_sound': False, 'full_logfile_path': 'C:\\Users\\dorus\\OneDrive\\Documents\\Pinball\\PortalPinball-V4.0\\machinefolder\\logs\\2024-09-07-19-47-26-mpf-Gaming_Dorus.log'}
2024-09-07 19:47:26,575 : INFO : Machine : MPF path: C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf
2024-09-07 19:47:26,575 : INFO : Machine : Machine path: C:\Users\dorus\OneDrive\Documents\Pinball\PortalPinball-V4.0\machinefolder
2024-09-07 19:47:26,575 : INFO : Machine : Platform: win32
2024-09-07 19:47:26,575 : INFO : Machine : Python executable location: C:\ProgramData\anaconda3\envs\mpfenv\python.exe
2024-09-07 19:47:26,575 : INFO : Machine : Python version: 3.12.4 (64-bit)
2024-09-07 19:47:26,577 : INFO : Machine : Initializing MPF...
2024-09-07 19:47:26,801 : INFO : EventManager : Event: ======'machine_var_credits_string'====== Args={'value': 'FREE PLAY', 'prev_value': None, 'change': True}
2024-09-07 19:47:26,822 : INFO : EventManager : Event: ======'machine_var_master_volume'====== Args={'value': 0.5, 'prev_value': None, 'change': True}
2024-09-07 19:47:26,822 : INFO : EventManager : Event: ======'machine_var_mpf_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev4', 'prev_value': None, 'change': True}
2024-09-07 19:47:26,822 : INFO : EventManager : Event: ======'machine_var_mpf_extended_version'====== Args={'value': 'Mission Pinball Framework v0.80.0.dev4, Config version:6, Show version: 6, BCP version:1.1', 'prev_value': None, 'change': True}
2024-09-07 19:47:26,822 : INFO : EventManager : Event: ======'machine_var_python_version'====== Args={'value': '3.12.4', 'prev_value': None, 'change': True}
2024-09-07 19:47:26,906 : INFO : EventManager : Event: ======'machine_var_platform'====== Args={'value': 'Windows-11-10.0.22631-SP0', 'prev_value': None, 'change': True}
2024-09-07 19:47:26,906 : INFO : EventManager : Event: ======'machine_var_platform_system'====== Args={'value': 'Windows', 'prev_value': None, 'change': True}
2024-09-07 19:47:26,906 : INFO : EventManager : Event: ======'machine_var_platform_release'====== Args={'value': '11', 'prev_value': None, 'change': True}
2024-09-07 19:47:26,906 : INFO : EventManager : Event: ======'machine_var_platform_version'====== Args={'value': '10.0.22631', 'prev_value': None, 'change': True}
2024-09-07 19:47:26,906 : INFO : EventManager : Event: ======'machine_var_platform_machine'====== Args={'value': 'AMD64', 'prev_value': None, 'change': True}
2024-09-07 19:47:26,906 : INFO : EventManager : Event: ======'machine_var_log_file_path'====== Args={'value': 'C:\\Users\\dorus\\OneDrive\\Documents\\Pinball\\PortalPinball-V4.0\\machinefolder\\logs\\2024-09-07-19-47-26-mpf-Gaming_Dorus.log', 'prev_value': None, 'change': True}
2024-09-07 19:47:26,906 : INFO : EventManager : Event: ======'init_phase_1'====== Args={}
2024-09-07 19:47:26,922 : ERROR : asyncio : Exception in callback EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...our config.')>) at C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\events.py:124
handle: <Handle EventManager._async_handler_done(<QueuedEvent>)(<Task finishe...our config.')>) at C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\events.py:124>
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\events.py", line 127, in _async_handler_done
    future.result()
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\device_manager.py", line 88, in _load_device_modules
    self.load_devices_config(validate=True)
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\device_manager.py", line 146, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 256, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 413, in _validate_type_machine
    raise self.validation_error(item, validation_failure_info,
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry drop_target_banks:db_dropbank:reset_coils = "c_drop" is not valid. Device "c_drop" not found in "coils:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)
2024-09-07 19:47:26,934 : INFO : Machine : Starting the main run loop.
2024-09-07 19:47:26,936 : INFO : Machine : Shutting down...
2024-09-07 19:47:26,936 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-09-07 19:47:27,951 : ERROR : Machine : Runtime Exception
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\machine.py", line 793, in _run_loop
    raise self._exception['exception']
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\events.py", line 127, in _async_handler_done
    future.result()
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\device_manager.py", line 88, in _load_device_modules
    self.load_devices_config(validate=True)
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\device_manager.py", line 146, in load_devices_config
    config[device_name] = collection[device_name].validate_and_parse_config(config[device_name], False)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\device.py", line 108, in validate_and_parse_config
    self.machine.config_validator.validate_config(
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 164, in validate_config
    return self._validate_config(config_spec, source, base_spec=base_spec, add_missing_keys=add_missing_keys,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 204, in _validate_config
    processed_config[k] = self.validate_config_item(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 256, in validate_config_item
    new_list.append(self.validate_item(i, validation, validation_failure_info))
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 699, in validate_item
    return self.validator_list[validator](item, validation_failure_info=validation_failure_info, param=param)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\config_validator.py", line 413, in _validate_type_machine
    raise self.validation_error(item, validation_failure_info,
mpf.exceptions.config_file_error.ConfigFileError: Config File Error in ConfigValidator: Config validation error: Entry drop_target_banks:db_dropbank:reset_coils = "c_drop" is not valid. Device "c_drop" not found in "coils:" section in your config. Error Code: CFE-ConfigValidator-6 (https://missionpinball.org/logs)
2024-09-07 19:47:27,956 : INFO : root : MPF run loop ended.
