2024-09-07 20:08:15,096 : INFO : root : Loading config.
2024-09-07 20:08:15,100 : INFO : YamlMultifileConfigLoader : Machine config file #1: config.yaml
2024-09-07 20:08:15,101 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\636ce416879e362e618e72aa23ee7aae.mpf_cache
2024-09-07 20:08:15,165 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\bb22be71dc4df7511e561cdf1fc10b40.mpf_cache
2024-09-07 20:08:15,166 : INFO : ConfigProcessor : Loading config from cache: C:\Users\dorus\AppData\Local\Temp\d8bc63701c1a2ad1653a8cc5aec9548a.mpf_cache
2024-09-07 20:08:15,166 : INFO : Machine : Mission Pinball Framework Core Engine v0.80.0.dev4
2024-09-07 20:08:15,166 : INFO : Machine : Command line arguments: {'no_load_cache': False, 'create_config_cache': True, 'bcp': False, 'configfile': ['config.yaml'], 'force_assets_load': False, 'platform_integration_test': False, 'jsonlogging': False, 'logfile': 'logs\\2024-09-07-20-08-15-mpf-Gaming_Dorus.log', 'pause': False, 'production': False, 'text_ui': False, 'loglevel': 15, 'consoleloglevel': 20, 'force_platform': None, 'syslog_address': None, 'mc_file_name': None, 'no_sound': False, 'full_logfile_path': 'C:\\Users\\dorus\\OneDrive\\Documents\\Pinball\\PortalPinball-V4.0\\machinefolder\\logs\\2024-09-07-20-08-15-mpf-Gaming_Dorus.log'}
2024-09-07 20:08:15,166 : INFO : Machine : MPF path: C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf
2024-09-07 20:08:15,166 : INFO : Machine : Machine path: C:\Users\dorus\OneDrive\Documents\Pinball\PortalPinball-V4.0\machinefolder
2024-09-07 20:08:15,166 : INFO : Machine : Platform: win32
2024-09-07 20:08:15,166 : INFO : Machine : Python executable location: C:\ProgramData\anaconda3\envs\mpfenv\python.exe
2024-09-07 20:08:15,166 : INFO : Machine : Python version: 3.12.4 (64-bit)
2024-09-07 20:08:15,168 : INFO : Machine : Initializing MPF...
2024-09-07 20:08:15,224 : INFO : OPP : Connecting to COM10 at 115200bps
2024-09-07 20:08:15,225 : INFO : Machine : Shutting down...
2024-09-07 20:08:15,225 : INFO : EventManager : Event: ======'shutdown'====== Args={}
2024-09-07 20:08:15,225 : ERROR : Machine : Failed to initialize MPF
Traceback (most recent call last):
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\machine.py", line 675, in initialize_mpf
    raise init.exception()
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\machine.py", line 247, in initialize
    await self.initialize_core_and_hardware()
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\machine.py", line 243, in initialize_core_and_hardware
    await self._initialize_platforms()
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\machine.py", line 333, in _initialize_platforms
    result.result()
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\platforms\opp\opp.py", line 107, in initialize
    await self._connect_to_hardware()
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\platforms\opp\opp.py", line 312, in _connect_to_hardware
    await comm.connect()
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\platforms\base_serial_communicator.py", line 47, in connect
    await self._connect_to_hardware(self.port, self.baud, self.xonxoff)
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\platforms\base_serial_communicator.py", line 56, in _connect_to_hardware
    self.reader, self.writer = await connector
                               ^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\mpf\core\clock.py", line 151, in open_serial_connection
    transport, _ = await create_serial_connection(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\serial_asyncio\__init__.py", line 448, in create_serial_connection
    serial_instance = serial.serial_for_url(*args, **kwargs)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\serial\__init__.py", line 90, in serial_for_url
    instance.open()
  File "C:\ProgramData\anaconda3\envs\mpfenv\Lib\site-packages\serial\serialwin32.py", line 64, in open
    raise SerialException("could not open port {!r}: {!r}".format(self.portstr, ctypes.WinError()))
serial.serialutil.SerialException: could not open port 'COM10': FileNotFoundError(2, 'The system cannot find the file specified.', None, 2)
2024-09-07 20:08:15,229 : INFO : root : MPF run loop ended.
